/**
 * @file bbs64.c
 * @brief BBS64 toy version.
 * @details Passes express, brief and default batteries, 16 GiB in PractRand.
 *
 * References:
 *
 * 1. L. Blum, M. Blum and M. Shub, "A Simple Unpredictable Pseudo-Random Number
 *    Generator" SIAM Journal on Computing, Vol. 15, No. 2, 1986, pp. 364-383.
 *    doi:10.1137/0215025
 * 2. http://www.ciphersbyritter.com/NEWS2/TESTSBBS.HTM
 *
 *
 * TestU01 Crush:
 *
 *          Test                          p-value
 *     ----------------------------------------------
 *      76  LongestHeadRun, r = 0           7.9e-8
 *     ----------------------------------------------
 *     All other tests were passed
 *
 * @copyright
 * (c) 2026 Alexey L. Voskov, Lomonosov Moscow State University.
 * alvoskov@gmail.com
 *
 * This software is licensed under the MIT license.
 */
#include "smokerand/cinterface.h"
#include "smokerand/int128defs.h"

PRNG_CMODULE_PROLOG

typedef struct {
    uint64_t x;
} Bbs64State;


static inline uint64_t get_bits_raw(Bbs64State *obj)
{
    static const uint64_t m = 4294967087ULL * 4294957307ULL;
    static const uint64_t d = 0ULL - m;

    uint64_t hi, lo;
    lo = unsigned_mul128(obj->x, obj->x, &hi);

    while (hi != 0) {
        lo = unsigned_muladd128(d, hi, lo, &hi);
    }
    if (lo >= m) {
        lo -= m;
    }
    obj->x = lo;
    return obj->x;
}


static void *create(const CallerAPI *intf)
{                                             
    Bbs64State *obj = intf->malloc(sizeof(Bbs64State));
    obj->x = (intf->get_seed32() >> 1) | 0x1;
    return obj;
}


/**
 * @brief Self-test to prevent problems during re-implementation
 * in MSVC and other plaforms that don't support int128.
 * @details The vector is generated by the next Python 3.x script:
 *
 *    m, x = 4294967087 * 4294957307, 2
 *    for i in range(10_000_000):
 *        xgood = (xgood * xgood) % m
 *    print(hex(xgood))
 */
static int run_self_test(const CallerAPI *intf)
{
    Bbs64State obj = {.x = 2};
    uint64_t u, u_ref = 0x4bab6b32a3cae1af;
    for (long i = 0; i < 10000000; i++) {
        u = get_bits_raw(&obj);
    }
    intf->printf("Result: %llX; reference value: %llX\n", u, u_ref);
    return u == u_ref;
}


MAKE_UINT64_PRNG("bbs64", run_self_test)
