/**
 * @file dandelion64.c
 * @brief dandelion64 is a xorshift-like LFSR that uses arithmetic right shift
 * and a non-bijective output scrambler.
 * @details This PRNG was designed by Aaron Pribadi. It uses the next
 * transition function and the next output function `F(x, y)`:
 *
 * - `T(x, y) = (y ^ lsl(x, sh1), x ^ asr(y, sh2)`
 * - `F(x, y) = ((x*x) % 2**32) + y) ^ ((x*x) // 2**32)`
 *
 * It has a proven period of \f$ 2^{64} - 1 \f$. Note: it also uses
 * an implementation defined behaviour of the `>>` operator for the signed
 * integers, but it is almost always implemented as an arithmetic shift.
 *
 * References:
 *
 * - https://github.com/apribadi/dandelion
 *
 * @copyright The dandelion64 PRNG was developed by Aaron Pribadi.
 *
 * Reentrant portable C99 implementation:
 *
 * (c) 2026 Alexey L. Voskov, Lomonosov Moscow State University.
 * alvoskov@gmail.com
 *
 * This software is licensed under the MIT license.
 */
#include "smokerand/cinterface.h"
#include "smokerand/int128defs.h"

PRNG_CMODULE_PROLOG

/**
 * @brief Dandelion64 PRNG state.
 */
typedef struct {
    uint32_t x;
    uint32_t y;
} Dandelion64State;


static inline uint64_t get_bits_raw(Dandelion64State *obj)
{
    const uint32_t x = obj->x, y = obj->y;
    obj->x = y ^ (x << 10);
    obj->y = x ^ (uint32_t) ((int32_t) y >> 7);
    const uint64_t xsq = (uint64_t) x * (uint64_t) x;
    const uint32_t hi = (uint32_t) (xsq >> 32), lo = (uint32_t) xsq;
    return (lo + y) ^ hi;
}


static void *create(const CallerAPI *intf)
{
    Dandelion64State *obj = intf->malloc(sizeof(Dandelion64State));
    seed64_to_2x32(intf, &obj->x, &obj->y);
    if (obj->x == 0 && obj->y == 0) {
        obj->x = 0xDEADBEEF;
        obj->y = 0x12345678;
    }
    return obj;    
}

/**
 * @brief An internal self-test based on values generated by custom
 * Python 3.x scripts (see `misc/lfsr/test_xorrot.py`)
 */
static int run_self_test(const CallerAPI *intf)
{
    const uint32_t x_ref = 0x2303d26e, y_ref = 0x17d31504, u_ref = 0x7D8760E8;
    Dandelion64State obj = {.x = 1, .y = 0};
    uint32_t u;
    for (long i = 0; i < 10000000; i++) {
        u = (uint32_t) get_bits_raw(&obj);
    }
    intf->printf("   %8s %8s\n", "out", "ref");
    intf->printf("x: %.8lX %.8lX\n",
        (unsigned long) obj.x, (unsigned long) x_ref);
    intf->printf("y: %.8lX %.8lX\n",
        (unsigned long) obj.y, (unsigned long) y_ref);
    intf->printf("u: %.8lX %.8lX\n",
        (unsigned long) u, (unsigned long) u_ref);
    return x_ref == obj.x && y_ref == obj.y && u == u_ref;
}


MAKE_UINT32_PRNG("dandelion64", run_self_test)
