/**
 * @file mwc192.c
 * @brief MWC192 - 192-bit PRNG based on MWC method.
 * @details Multiply-with-carry PRNG with a period about 2^191.
 * Passes SmallCrush, Crush and BigCrush tests.
 *
 *    import sympy
 *    a, b = 0xffa04e67b3c95d86, 2**64
 *    m = a*b**2 - 1
 *    print(hex(m))
 *    print(sympy.isprime(m), sympy.n_order(b, m) / m)
 *    x = b**2 + b*0x87654321 + 0x12345678
 *    mul = pow(b, -1, m)
 *    print("mul: ", hex(mul))
 *    for i in range(1000000):
 *        x = (mul * x) % m
 *    for i in range(20):
 *        print("--->", hex((x // 2**64) % 2**64), hex(x))
 *        x = (mul * x) % m
 *
 * References:
 *
 * 1. Sebastiano Vigna. MWC192. https://prng.di.unimi.it/MWC192.c
 *
 * @copyright
 * (c) 2024-2026 Alexey L. Voskov, Lomonosov Moscow State University.
 * alvoskov@gmail.com
 *
 * This software is licensed under the MIT license.
 */
#include "smokerand/cinterface.h"
#include "smokerand/int128defs.h"

PRNG_CMODULE_PROLOG

/**
 * The state must be initialized so that 0 < c < MWC_A2 - 1.
 * For simplicity, we suggest to set c = 1 and x, y to a 128-bit seed.
 */
typedef struct {
    uint64_t x; ///< x_{n-2}
    uint64_t y; ///< x_{n-1}
    uint64_t c; ///< carry
} MWC192State;

#define MWC_A2 0xffa04e67b3c95d86

/**
 * @brief MWC192 PRNG implementation.
 */
static inline uint64_t get_bits_raw(MWC192State *obj)
{
    const uint64_t result = obj->y;
    // muladd128() returns the high bits, and puts the low bits in the last param
    const uint64_t t      = unsigned_muladd128(MWC_A2, obj->x, obj->c, &obj->c);

    obj->x = obj->y;
    obj->y = t;
    // C is set to the lower bits in the muladd128() above

    return result;
}

/**
 * @brief An internal self-test with test values generated by the Python
 * script that implements MWC192 as LCG.
 */
static int run_self_test(const CallerAPI *intf)
{
    static const uint64_t u_ref[] = {
        0xc910be04d4ea5247, 0xf9c7e6123fce120e, 0xd2488e39e1573bba,
        0x3d175b1b595bcd04, 0x639da0dba74e59ff, 0xfb27a13cb9837e4b,
        0xf7b690db0c1568a8, 0xa6711d292fec2eda, 0xffe8e5ecd154607c,
        0x8c8d3d23cc4f1ead
    };
    MWC192State obj = {.x = 0x12345678, .y = 0x87654321, .c = 1};
    int is_ok = 1;
    for (long i = 0; i < 1000000; i++) {
        (void) get_bits_raw(&obj);
    }
    intf->printf("%18s %18s\n", "Output", "Reference");
    for (int i = 0; i < 10; i++) {
        const uint64_t u = get_bits_raw(&obj);
        intf->printf("0x%.16llX 0x%.16llX\n",
            (unsigned long long) u, (unsigned long long) u_ref[i]);
        if (u_ref[i] != u) {
            is_ok = 0;
        }
    }
    return is_ok;
}


static void *create(const CallerAPI *intf)
{
    MWC192State *obj = intf->malloc(sizeof(MWC192State));

    obj->x = intf->get_seed64();
    obj->y = intf->get_seed64();
    obj->c = 1;

    return obj;
}

MAKE_UINT64_PRNG("MWC192", run_self_test)
