/**
 * @file pqrnd64.c
 * @brief A nonlinear 32-bit generator with an invertible mapping.
 * @details This PRNG is developed by Karl-Uwe Frank and is based
 * on a nonlinear invertible mapping. See details in the `pqrng32.c`
 * file.
 *
 * 1. http://www.freecx.co.uk/pqRNG/
 * 2. V. S. Anachin. Uniformly distributed sequences of p-adic integers //
 *    Mathematical Notes. 1994. V. 55. P. 109–133.
 *    https://doi.org/10.1007/BF02113290 
 *
 * @copyright pqrng algorithm was developed by Karl-Uwe Frank and is based
 * on invertible mappings suggested by V. S. Anashin.
 *
 * Reentrant C99 implementation for SmokeRand:
 *
 * (c) 2026 Alexey L. Voskov, Lomonosov Moscow State University.
 * alvoskov@gmail.com
 *
 * This software is licensed under the MIT license.
 */
#include "smokerand/cinterface.h"
#include "smokerand/int128defs.h"

PRNG_CMODULE_PROLOG

typedef Lcg128State Pqrng128State;

static inline uint64_t get_bits_raw(Pqrng128State *obj)
{
    static const uint64_t r = 0x517CC1B727220A95; // (mod8 = 5)
    static const uint64_t p = 0x9E3779B97F4A7C13; // (mod8 = 3)
    // obj->x = (obj->x ^ r) * p;
    uint64_t mul0_high;
    obj->x_low ^= r;
    obj->x_high ^= r;
    obj->x_low = unsigned_mul128(p, obj->x_low, &mul0_high);
    obj->x_high = p * obj->x_high + mul0_high;
    return obj->x_high;
}


static void *create(const CallerAPI *intf)
{
    Pqrng128State *obj = intf->malloc(sizeof(Pqrng128State));
    obj->x_high = intf->get_seed64();
    obj->x_low = intf->get_seed64();
    return obj;
}

/**
 * @brief An internal self-test that uses the test values generated by the next
 * Python 3.x script:
 *
 *    x = 123456789
 *    r, p = 0x517CC1B727220A95, 0x9E3779B97F4A7C13
 *    for i in range(10001):
 *        x = (p * (x ^ (r * 2**64 + r))) % 2**128
 *    print(hex(x // 2**64), hex(x))
 */
static int run_self_test(const CallerAPI *intf)
{
    Pqrng128State obj = {.x_low = 123456789, .x_high = 0};
    const uint64_t u_ref = 0xfca6c45fab770809;
    for (int i = 0; i < 10000; i++) {
        (void) get_bits_raw(&obj);
    }
    const uint64_t u = get_bits_raw(&obj);
    intf->printf("Out=0x%llX; ref=0x%llX\n",
        (unsigned long long) u, (unsigned long long) u_ref);
    return u == u_ref ? 1 : 0;
    
}


MAKE_UINT64_PRNG("PQRNG128", run_self_test)
